name: Generar Lote de Retos (Manual)

on:
  workflow_dispatch:
    inputs:
      retos_por_categoria:
        description: '¿Cuántos retos generar por cada categoría?'
        required: true
        default: '5'

jobs:
  generate-batch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout de la rama develop
        uses: actions/checkout@v4
        with:
          ref: 'develop'

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install google-generativeai firebase-admin

      - name: Ejecutar script de generación en lote
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          FIREBASE_CREDS: ${{ secrets.FIREBASE_CREDS }}
          GENERATION_MODE: 'bulk' # Le decimos al script que queremos generar en lote
          COUNT_PER_CATEGORY: ${{ github.event.inputs.retos_por_categoria }}
        run: python reto_diario.py

      - name: Guardar los nuevos retos en la rama develop
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git pull
          git add almacen_retos/*
          git commit -m "🤖 Lote de ${{ github.event.inputs.retos_por_categoria }} retos por categoría generado" || echo "No hay cambios para commitear"
          git push