name: Generador de Contenido

on:
  # Se activa solo cuando t칰 le das al bot칩n en la pesta침a "Actions"
  workflow_dispatch:

jobs:
  generar-retos:
    runs-on: ubuntu-latest
    steps:
      # Descarga la 칰ltima versi칩n de tu c칩digo
      - name: Checkout de la rama main
        uses: actions/checkout@v4

      # Configura Python
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Instala las librer칤as necesarias
      - name: Instalar dependencias
        run: pip install -r requirements.txt

      # Ejecuta el script de Python para generar el lote de retos
      - name: Ejecutar el generador de retos
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python3 reto_diario.py

      # Sube la carpeta 'almacen_retos' con el nuevo contenido
      - name: Guardar los nuevos retos en el repositorio
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add almacen_retos/
          git commit -m "游뱄 Lote de retos generado autom치ticamente" || echo "No hay nuevos retos para guardar."
          git push